export const gameState = {
  title: "HANGMAN",
  puzzles: [
    {
      category: "MOVIES",
      questions: [
        "MATRIX",
        "WANTED",
        "LORD OF THE RINGS",
        "TRANSFORMERS",
        "THE SHAWSHANK REDEMPTION",
        "FORREST GUMP",
        "DUMB AND DUMBER",
        "PAPILLON",
        "CATCH ME IF YOU CAN",
        "THE HUNGER GAMES",
        "BLOODSHOT",
        "THE DARK KNIGHT",
        "FIGHT CLUB",
        "DIE HARD",
        "TITANIC",
        "THE SILENCE OF THE LAMBS",
      ],
    },
    {
      category: "TV SERIES",
      questions: [
        "PEAKY BLINDERS",
        "LUCIFER",
        "EMILY IN PARIS",
        "FRIENDS",
        "TWO AND A HALF MEN",
        "STRANGER THINGS",
        "PUNISHER",
        "GOTHAM",
        "MONEY HEIST",
        "MIRZAPUR",
      ],
    },
    {
      category: "DAILY",
      questions: [
        "TOOTHPASTE",
        "SUNLIGHT",
        "MOBILE PHONE",
        "MILK",
        "BEDROOM",
        "GROCERY",
        "KEYS",
        "REFRIGERATOR",
        "METRO",
        "LAPTOP",
      ],
    },
    {
      category: "CARS",
      questions: [
        "VOLKSWAGEN",
        "FORD",
        "NISSAN",
        "RENAULT",
        "CHEVROLET",
        "TESLA",
        "LAMBORGHINI",
        "BUGGATI",
        "HYUNDAI",
        "TOYOTA",
      ],
    },
  ],
  currCat: "",
  questions: [],
  guessedLetters: [],
  correctGuesses: [],
  questionCount: 0,
  wrongAttempts: 0,
  currentPuzzle: "",
  reqNbGuesses: 0,
  score: 0,
};
